POST http://localhost:3003/turma
Content-Type: application/json

{
    "id":2,
    "nome": "bouman",
    "data_inicio":"2019-09-01",
    "data_fim":"2020-03-01",
    "tipo": "noturno"
}

###

POST http://localhost:3003/estudante
Content-Type: application/json

{
    "id": 1,
    "nome": "caio",
    "email": "caio@email.com",
    "data_nasc":"1997-07-10",
    "hobbies": ["jogar","Cuidar do Lupin","aprontar"],
    "turma_id":1
}


###
POST http://localhost:3003/docente
Content-Type: application/json 

{
    "id": 2 ,
    "nome": "monaliza",
    "email": "monaliza@email.com",
    "data_nasc":"1997-07-10",
    "especialidades": ["CSS","REACT","REDUX"],
    "turma_id":2

}

### 
Put http://localhost:3003/docente
Content-Type: application/json

{
    "docente_id":2,
    "turma_id":9
}

### 
Put http://localhost:3003/estudante
Content-Type: application/json

{
    "estudante_id":1,
    "turma_id":9
}

###
GET http://localhost:3003/estudante/5
Content-Type: application/json
